# Generated by Django 4.0.4 on 2022-06-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0003_create_stockcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_stockgrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('quntities_added', models.CharField(max_length=225)),
            ],
        ),
    ]
