# Generated by Django 4.0.4 on 2022-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0005_create_units_create_vouchermodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_stockitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('category', models.CharField(max_length=225)),
                ('units', models.CharField(max_length=225)),
                ('rate_of_duty', models.CharField(max_length=225)),
            ],
        ),
    ]
