# Generated by Django 4.0.4 on 2022-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0006_create_stockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_goddown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
            ],
        ),
    ]
