# Generated by Django 4.0.4 on 2022-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0007_create_goddown'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_units',
            name='conversion',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='create_units',
            name='first_unit',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='create_units',
            name='second_unit',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
