# Generated by Django 4.0.4 on 2022-07-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0009_alter_create_units_formal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_units',
            name='conversion',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='first_unit',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='formal_name',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='number_of_decimal_places',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='second_unit',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='symbol',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
        migrations.AlterField(
            model_name='create_units',
            name='type',
            field=models.CharField(blank=True, default='false', max_length=225),
        ),
    ]
