# Generated by Django 4.0.4 on 2022-07-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0012_create_payhead_rounding_compute_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounding',
            old_name='ledger_id',
            new_name='pay_head_id',
        ),
    ]
