# Generated by Django 4.0.4 on 2022-07-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0014_gratuity'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acount_No', models.CharField(max_length=225)),
                ('IFSC_code', models.CharField(max_length=225)),
                ('Bank_name', models.CharField(max_length=225)),
                ('Branch_name', models.CharField(max_length=225)),
                ('Transaction_type', models.CharField(max_length=225)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.employee')),
            ],
        ),
    ]
