# Generated by Django 4.0.4 on 2022-07-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0016_e_found_trasfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_stockitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='create_stockitem',
            name='rate_of_duty',
        ),
        migrations.AddField(
            model_name='create_stockitem',
            name='maintain_matches',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='create_stockitem',
            name='track_date_of_manufaturing',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='create_stockitem',
            name='use_expiry_dates',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
