# Generated by Django 4.0.4 on 2022-07-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0017_remove_create_stockitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_stockitem',
            old_name='maintain_matches',
            new_name='maintain_Batches',
        ),
    ]
