# Generated by Django 4.0.4 on 2022-07-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0018_rename_maintain_matches_create_stockitem_maintain_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_attendence',
            name='period',
            field=models.CharField(blank=True, default='null', max_length=225),
        ),
        migrations.AddField(
            model_name='create_attendence',
            name='units',
            field=models.CharField(blank=True, default='null', max_length=225),
        ),
    ]
