# Generated by Django 4.0.4 on 2022-08-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0019_create_attendence_period_create_attendence_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('effective', models.CharField(max_length=225)),
                ('payhead', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('per', models.CharField(max_length=225)),
                ('pay_type', models.CharField(max_length=225)),
                ('cal_type', models.CharField(max_length=225)),
            ],
        ),
    ]
